# Generated by Django 3.2.8 on 2021-11-19 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_anime_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='epsT',
            field=models.PositiveIntegerField(verbose_name='Episódios Totais'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='estudio',
            field=models.ManyToManyField(related_name='animes', to='core.Estudio', verbose_name='Estúdio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genero',
            field=models.ManyToManyField(related_name='animes', to='core.Genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titulo',
            field=models.CharField(max_length=255, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lista', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='listaanimes',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anime', unique=True),
        ),
        migrations.AlterField(
            model_name='listaanimes',
            name='eps',
            field=models.PositiveIntegerField(verbose_name='Episódios'),
        ),
        migrations.AlterField(
            model_name='listaanimes',
            name='status',
            field=models.CharField(choices=[('Assistindo', 'Assistindo'), ('Completo', 'Completo'), ('Quero assistir', 'Quero Assistir'), ('Desisti', 'Desisti')], default='Assistindo', max_length=255, verbose_name='Status'),
        ),
    ]
