# Generated by Django 3.2.8 on 2021-11-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211119_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaanimes',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anime'),
        ),
    ]
